---
version: 2.1
executors:
  linux-x86_64:
    docker:
      - image: cimg/deploy:2025.01.1
  linux-aarch64:
    resource_class: arm.medium
    docker:
      - image: cimg/deploy:2025.01.1
jobs:
  test:
    executor: linux-x86_64
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_TOKEN}"
      - run:
          name: Build test image
          command: docker image build --target=test --tag=sardylan/tournaments-mgmt-webapp:${CIRCLE_SHA1}-test .
      - run:
          name: Run tests
          command: docker container run --tty --rm sardylan/tournaments-mgmt-webapp:${CIRCLE_SHA1}-test
  build:
    executor: linux-x86_64
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_TOKEN}"
      - run:
          name: Build image
          command: docker image build --target=prod --tag=sardylan/tournaments-mgmt-webapp:${CIRCLE_SHA1} .
      - run:
          name: Tag image and push
          command: |
            docker image tag sardylan/tournaments-mgmt-webapp:${CIRCLE_SHA1} sardylan/tournaments-mgmt-webapp:${CIRCLE_TAG}
            docker image push sardylan/tournaments-mgmt-webapp:${CIRCLE_TAG}
workflows:
  test:
    jobs:
      - test:
          context:
            - "Docker Hub"
          filters:
            branches:
              only: main
  test_build:
    jobs:
      - test:
          context:
            - "Docker Hub"
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - build:
          context:
            - "Docker Hub"
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
