---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tournaments-mgmt-webapp.fullname" . }}
  labels:
    {{- include "tournaments-mgmt-webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.http.port }}
      targetPort: 80
  selector:
    {{- include "tournaments-mgmt-webapp.selectorLabels" . | nindent 4 }}
